### ISSUE TITLE
any Documentation?

### ISSUE THREAD

**Issue by bahmani00** [HamedFathi/LoadEngine#1]
Hi Hamed

Is it possible to briefly explain what this project doing?

Appriciated
Dan

**Comment by HamedFathi** [comment]
@bahmani00 

Please use [DotNetCorePlugins](https://github.com/natemcmaster/DotNetCorePlugins) especially after these topics [Hot reloading plugins in .NET Core 3](https://github.com/natemcmaster/DotNetCorePlugins/issues/37) and [LoadInMemory](https://github.com/natemcmaster/DotNetCorePlugins/pull/133)
